import "@testing-library/jest-dom/vitest";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import MatrixCopilotPanel from "./MatrixCopilotPanel";
import { apiFetch } from "../../../services/apiClient";

vi.mock("../../../services/apiClient", () => ({ API_BASE_URL: "http://localhost:3000", apiFetch: vi.fn() }));
const payload = { workflow: "MATRIX_AUDIT", readOnly: true, audit: { coveragePct: 50, activeCells: 2, totalCells: 4, sitOutCells: 1, idleCapitalPct: 20, unusedStrategies: [{ strategyName: "Defensive" }], guardrailsValid: true }, response: { executiveSummary: "The matrix is concentrated in Technology.", keyFindings: ["Coverage is partial."], matrixOverview: {}, cellAnalysis: [{ cellKey: "Technology::BULL", sector: "Technology", regime: "BULL", status: "ACTIVE", strategy: "Momentum", finding: "This cell is active.", evidenceStrength: "HIGH" }], strategyAnalysis: ["Momentum is reused."], allocationAnalysis: ["Twenty percent is idle."], replayEvidence: [], portfolioInteraction: [], currentDeployment: [], risks: ["Sector concentration."], evidence: [{ sourceType: "MATRIX_CONFIGURATION", sourceId: "dep-1", metricName: "CoveragePct", metricValue: "50", interpretation: "Deterministic coverage." }], confidenceScore: 78, limitations: ["No saved matrix replay is available."], suggestedInvestigations: ["Run Matrix Replay explicitly."] } };

describe("MatrixCopilotPanel", () => { beforeEach(() => vi.clearAllMocks()); afterEach(cleanup);
  it("renders read-only matrix audit results and evidence", async () => { apiFetch.mockResolvedValue({ ok: true, json: async () => payload }); render(<MatrixCopilotPanel />); fireEvent.click(screen.getByRole("button", { name: "Matrix Audit" })); fireEvent.click(screen.getByRole("button", { name: "Analyze Matrix" })); await screen.findByText("The matrix is concentrated in Technology."); expect(screen.getByText("50%")).toBeInTheDocument(); expect(screen.getByText("This cell is active.")).toBeInTheDocument(); expect(screen.getByText(/CoveragePct: 50/i)).toBeInTheDocument(); expect(screen.queryByRole("button", { name: /save changes|apply changes|activate strategy|optimize allocation/i })).not.toBeInTheDocument(); });
  it("validates questions and submits the selected mode", async () => { apiFetch.mockResolvedValue({ ok: true, json: async () => payload }); render(<MatrixCopilotPanel />); fireEvent.click(screen.getByRole("button", { name: "Ask Matrix Copilot" })); fireEvent.click(screen.getByRole("button", { name: "Analyze Matrix" })); expect(screen.getByText("Enter a matrix question.")).toBeInTheDocument(); fireEvent.change(screen.getByLabelText("Ask about the current matrix"), { target: { value: "Where is risk concentrated?" } }); fireEvent.click(screen.getByRole("button", { name: "Analyze Matrix" })); await screen.findByText("The matrix is concentrated in Technology."); expect(JSON.parse(apiFetch.mock.calls[0][1].body)).toEqual({ workflow: "MATRIX_QUESTION", question: "Where is risk concentrated?" }); });
  it("renders a simulated proposal, deterministic comparison, and matrix diff", async () => { const scenario = { advisoryOnly: true, noChangesApplied: true, proposal: { title: "Sit out weak cell", actions: [{ actionType: "SET_CELL_TO_SIT_OUT", sector: "Technology", regime: "BEAR", currentStrategyId: "s-1", proposedStrategyId: "", currentAllocation: 20, proposedAllocation: 0, reason: "Weak evidence." }] }, comparison: { simulationMethod: "HISTORICAL_MATRIX_REPLAY", current: { replay: { totalReturnPct: 5, sharpe: 1, maxDrawdownPct: 8, completedTrades: 20, transactionCosts: 7 } }, proposed: { replay: { totalReturnPct: 7, sharpe: 1.2, maxDrawdownPct: 6, completedTrades: 18, transactionCosts: 5 } }, matrixDiff: [{ before: { key: "Technology::BEAR", sector: "Technology", regime: "BEAR", strategyName: "Momentum", allocationPct: 20 }, after: { key: "Technology::BEAR", sector: "Technology", regime: "BEAR", strategyName: null, allocationPct: 0 } }] }, response: { executiveSummary: "The scenario lowers drawdown.", confidenceScore: 78, benefits: ["Lower drawdown."], risksTradeoffs: ["Fewer trades."], replayEvidence: ["Historical replay."], portfolioImpact: ["Lower exposure."] } }; apiFetch.mockResolvedValue({ ok: true, json: async () => scenario }); render(<MatrixCopilotPanel />); fireEvent.click(screen.getByRole("button", { name: "Simulate" })); fireEvent.change(screen.getByLabelText("Matrix objective"), { target: { value: "Set low-evidence cells to Sit Out." } }); fireEvent.click(screen.getByRole("button", { name: "Run Scenario" })); await screen.findByText("The scenario lowers drawdown."); expect(screen.getByText("NO CHANGES APPLIED")).toBeInTheDocument(); expect(screen.getByText("Momentum (20%)")).toBeInTheDocument(); expect(screen.getByText("Sit out (0%)")).toBeInTheDocument(); expect(apiFetch.mock.calls[0][0]).toContain("/api/strategy-lab/matrix-copilot/scenario"); });
});
