const test = require("node:test");
const assert = require("node:assert/strict");
const { createMatrixAdvisorService } = require("../features/strategyLab/services/matrixAdvisor.service");

const evidence = { sourceType: "MATRIX_CONFIGURATION", sourceId: "dep-1", metricName: "CoveragePct", metricValue: "50", timestamp: "", dateRange: "", interpretation: "Coverage.", strength: "HIGH" };
const proposal = { proposalType: "COVERAGE", title: "Sit out weak cell", objective: "Reduce weak coverage", deploymentSetId: "dep-1", actions: [{ actionType: "SET_CELL_TO_SIT_OUT", sector: "Technology", regime: "BEAR", currentStrategyId: "s-1", currentStrategyVersionId: "v-1", proposedStrategyId: "", proposedStrategyVersionId: "", currentAllocation: 20, proposedAllocation: 0, reason: "Weak evidence." }], assumptions: [], evidence: [evidence], confidence: 0.8 };
const context = { dashboard: { deploymentSetId: "dep-1" }, audit: {}, latestReplay: {}, availableEvidence: [evidence], limitations: [], workflow: "MATRIX_AUDIT" };
const comparison = { simulationMethod: "HISTORICAL_MATRIX_REPLAY", current: { replay: { totalReturnPct: 5 }, portfolio: {} }, proposed: { replay: { totalReturnPct: 7 }, portfolio: { metrics: {} }, audit: { activeCells: 1, sitOutCells: 2 } }, delta: { replay: { totalReturnPct: 2 } }, matrixDiff: [], replayAvailable: true };

test("matrix recommendation is evidence grounded and advisory only", async () => { const service = createMatrixAdvisorService({ matrixCopilotService: { buildContext: async () => context }, scenarioService: {}, aiService: { matrixRecommendation: async () => ({ executiveSummary: "Review weak cells.", concern: "Low coverage evidence.", recommendation: "Simulate Sit Out.", proposedActions: proposal.actions, rationale: [], expectedBenefits: [], potentialDownsides: [], assumptions: [], requiredValidation: [], replayAvailable: true, evidence: [evidence], confidenceScore: 0.82, limitations: [] }) } }); const result = await service.recommend("u-1", { question: "Improve weak cells" }); assert.equal(result.advisoryOnly, true); assert.equal(result.noChangesApplied, true); assert.equal(result.response.confidenceScore, 82); assert.equal(result.response.evidence[0].metricValue, "50"); });

test("matrix scenario validates an AI proposal before deterministic simulation and interpretation", async () => { let simulated = false; const service = createMatrixAdvisorService({ matrixCopilotService: { buildContext: async () => context }, scenarioService: { simulate: async ({ proposal: input }) => { simulated = true; assert.equal(input.confidence, 80); return comparison; } }, aiService: { matrixScenarioProposal: async () => structuredClone(proposal), matrixScenarioInterpretation: async (_userId, input) => ({ executiveSummary: "The scenario improves replay return.", matrixConcernObjective: "Weak cell", recommendation: "Review the simulation.", proposedCellChanges: [], comparisonFindings: [], replayEvidence: [], portfolioImpact: [], benefits: [], risksTradeoffs: [], evidence: [input.availableEvidence.find((item) => item.sourceId.startsWith("scenario:"))], confidenceScore: 75, limitations: [], availableUserActions: ["Discard"] }) } }); const result = await service.scenario("u-1", { question: "Set weak cells to Sit Out" }); assert.equal(simulated, true); assert.equal(result.noChangesApplied, true); assert.equal(result.comparison.delta.replay.totalReturnPct, 2); assert.equal(result.response.evidence[0].sourceType, "MATRIX_REPLAY"); });

test("alternative comparison ranks only deterministically simulated proposals", async () => { let calls = 0; const second = { ...proposal, title: "Reduce allocation", proposalType: "ALLOCATION", actions: [{ ...proposal.actions[0], actionType: "SET_CELL_ALLOCATION", proposedAllocation: 10 }] }; const service = createMatrixAdvisorService({ matrixCopilotService: { buildContext: async () => context }, scenarioService: { simulate: async () => { calls += 1; return comparison; } }, aiService: { matrixAlternativeComparison: async () => ({ executiveSummary: "Option one has stronger evidence.", rankings: [{ proposalIndex: 0, title: proposal.title, rationale: "Replay result.", riskImpact: "Lower", portfolioImpact: "Neutral", turnover: "Available", implementationComplexity: "LOW", evidenceQuality: "HIGH", confidenceScore: 80, tradeoffs: [] }, { proposalIndex: 1, title: second.title, rationale: "Less disruption.", riskImpact: "Neutral", portfolioImpact: "Neutral", turnover: "Available", implementationComplexity: "LOW", evidenceQuality: "HIGH", confidenceScore: 70, tradeoffs: [] }], evidence: [], limitations: [] }) } }); const result = await service.compare("u-1", { proposals: [structuredClone(proposal), second] }); assert.equal(calls, 2); assert.equal(result.comparisons.length, 2); assert.equal(result.noChangesApplied, true); });
