const test = require("node:test");
const assert = require("node:assert/strict");
const { applyProposal, createMatrixScenarioService } = require("../features/strategyLab/services/matrixScenario.service");
const { validateMatrixProposalShape } = require("../features/strategyLab/services/matrixScenarioContract");

function dashboard() { return { generatedAt: "2026-07-11T04:00:00Z", deploymentSetId: "dep-1", guardrails: { config: { minimumTrades: 0, minimumValidationScore: 0, minimumRobustness: 0, minimumWalkForwardStability: 0, maxStrategyAllocationPct: 100, maxSectorExposurePct: 60 }, valid: true }, strategies: [{ experimentId: "s-1", strategyVersionId: "v-1", name: "Momentum", status: "READY", readinessScore: 80, assignedCapitalPct: 50, maxAllocationPct: 100, hasValidatedEvidence: true, walkForwardPassed: true, robustnessPassed: true, tradeCountPassed: true, validationScorePassed: true }, { experimentId: "s-2", strategyVersionId: "v-2", name: "Defensive", status: "READY", readinessScore: 70, assignedCapitalPct: 30, maxAllocationPct: 100, hasValidatedEvidence: true, walkForwardPassed: true, robustnessPassed: true, tradeCountPassed: true, validationScorePassed: true }, { experimentId: "s-3", strategyVersionId: "v-3", name: "Blocked", status: "BLOCKED", readinessScore: 0, assignedCapitalPct: 0, maxAllocationPct: 100 }], matrix: { sectors: ["Technology", "Healthcare"], regimes: ["BULL", "BEAR"], cells: [{ key: "Technology::BULL", sector: "Technology", regime: "BULL", status: "ACTIVE", selectedExperimentId: "s-1", selectedStrategyVersionId: "v-1", strategyName: "Momentum", allocationPct: 30 }, { key: "Technology::BEAR", sector: "Technology", regime: "BEAR", status: "ACTIVE", selectedExperimentId: "s-1", selectedStrategyVersionId: "v-1", strategyName: "Momentum", allocationPct: 20 }, { key: "Healthcare::BULL", sector: "Healthcare", regime: "BULL", status: "SIT_OUT", selectedExperimentId: null, selectedStrategyVersionId: null, allocationPct: 0 }, { key: "Healthcare::BEAR", sector: "Healthcare", regime: "BEAR", status: "ACTIVE", selectedExperimentId: "s-2", selectedStrategyVersionId: "v-2", strategyName: "Defensive", allocationPct: 30 }] }, simulation: { metrics: { expectedReturn: 7, expectedDrawdown: 9, sharpe: 1, capitalUsage: 80 } } }; }
function proposal(action, type = "CELL_CHANGE") { return { proposalType: type, title: "Scenario", objective: "Test a matrix change", deploymentSetId: "dep-1", actions: [{ actionType: action.actionType, sector: action.sector || "", regime: action.regime || "", currentStrategyId: action.currentStrategyId || "", currentStrategyVersionId: action.currentStrategyVersionId || "", proposedStrategyId: action.proposedStrategyId || "", proposedStrategyVersionId: action.proposedStrategyVersionId || "", currentAllocation: action.currentAllocation ?? 0, proposedAllocation: action.proposedAllocation ?? 0, reason: "Evidence-backed scenario." }], assumptions: [], evidence: [], confidence: 75 }; }

test("proposal contract rejects unsupported actions", () => { assert.throws(() => validateMatrixProposalShape({ ...proposal({ actionType: "HACK" }), actions: [{ ...proposal({ actionType: "HACK" }).actions[0], actionType: "HACK" }] }), /unsupported matrix action/i); });
test("cell replacement and Sit Out scenarios apply only to cloned matrices", () => { const current = dashboard(); const replaced = applyProposal(current, proposal({ actionType: "REPLACE_STRATEGY", sector: "Technology", regime: "BEAR", currentStrategyId: "s-1", currentStrategyVersionId: "v-1", proposedStrategyId: "s-2", proposedStrategyVersionId: "v-2", currentAllocation: 20, proposedAllocation: 15 })); assert.equal(replaced.matrix.cells[1].selectedExperimentId, "s-2"); assert.equal(current.matrix.cells[1].selectedExperimentId, "s-1"); const satOut = applyProposal(current, proposal({ actionType: "SET_CELL_TO_SIT_OUT", sector: "Technology", regime: "BEAR", currentStrategyId: "s-1", currentAllocation: 20 })); assert.equal(satOut.matrix.cells[1].status, "SIT_OUT"); assert.equal(satOut.matrix.cells[1].allocationPct, 0); });
test("allocation and sector-cap scenarios are deterministic", () => { const allocated = applyProposal(dashboard(), proposal({ actionType: "SET_CELL_ALLOCATION", sector: "Technology", regime: "BEAR", currentStrategyId: "s-1", currentAllocation: 20, proposedAllocation: 10 }, "ALLOCATION")); assert.equal(allocated.matrix.cells[1].allocationPct, 10); const capped = applyProposal(dashboard(), proposal({ actionType: "SET_SECTOR_CAP", sector: "Technology", currentAllocation: 50, proposedAllocation: 25 }, "DIVERSIFICATION")); assert.equal(capped.validation.sectorExposure.Technology, 25); });
test("ownership, lifecycle eligibility, and stale strategy versions fail validation", () => { assert.throws(() => applyProposal(dashboard(), proposal({ actionType: "REPLACE_STRATEGY", sector: "Technology", regime: "BEAR", currentStrategyId: "s-1", proposedStrategyId: "foreign", proposedStrategyVersionId: "v-x", currentAllocation: 20, proposedAllocation: 10 })), /not owned/i); assert.throws(() => applyProposal(dashboard(), proposal({ actionType: "REPLACE_STRATEGY", sector: "Technology", regime: "BEAR", currentStrategyId: "s-1", proposedStrategyId: "s-2", proposedStrategyVersionId: "stale", currentAllocation: 20, proposedAllocation: 10 })), /stale/i); assert.throws(() => applyProposal(dashboard(), proposal({ actionType: "REPLACE_STRATEGY", sector: "Technology", regime: "BEAR", currentStrategyId: "s-1", proposedStrategyId: "s-3", proposedStrategyVersionId: "v-3", currentAllocation: 20, proposedAllocation: 10 })), /not lifecycle/i); });
test("scenario simulation reuses replay config and never persists deployment state", async () => { let replayCalls = 0; const service = createMatrixScenarioService({ runMatrixReplay: async ({ matrixOverride, body }) => { replayCalls += 1; assert.equal(matrixOverride.cells[1].status, "SIT_OUT"); assert.deepEqual(body.symbols, ["NVDA"]); return { result: { total_return_pct: 8, sharpe: 1.3, max_drawdown_pct: 6, completed_trades: 20, total_fees_paid: 5, estimated_slippage_cost: 2 } }; } }); const result = await service.simulate({ userId: "u-1", dashboard: dashboard(), latestReplay: { createdAt: "2026-07-11T03:00:00Z", replayConfigJson: { symbols: ["NVDA"], period: "1y" }, resultJson: { total_return_pct: 5, sharpe: 1, max_drawdown_pct: 8, completed_trades: 18 } }, proposal: proposal({ actionType: "SET_CELL_TO_SIT_OUT", sector: "Technology", regime: "BEAR", currentStrategyId: "s-1", currentAllocation: 20 }) }); assert.equal(replayCalls, 1); assert.equal(result.simulationMethod, "HISTORICAL_MATRIX_REPLAY"); assert.equal(result.delta.replay.totalReturnPct, 3); assert.equal(result.matrixDiff.length, 1); });
