const { requireUserId } = require("../../../repositories/ownership");
const { createEvidenceItem, normalizeEvidenceReferences } = require("./strategyCopilotEvidence.service");

const MATRIX_WORKFLOWS = Object.freeze(["MATRIX_AUDIT", "MATRIX_EXPLANATION", "MATRIX_REPLAY_ANALYSIS", "MATRIX_DEPLOYMENT_ANALYSIS", "MATRIX_ALLOCATION_ANALYSIS", "MATRIX_COVERAGE_ANALYSIS", "MATRIX_RISK_ANALYSIS", "MATRIX_QUESTION"]);
const FEATURE_METHODS = Object.freeze({ MATRIX_AUDIT: "matrixAudit", MATRIX_EXPLANATION: "matrixExplanation", MATRIX_REPLAY_ANALYSIS: "matrixReplayAnalysis", MATRIX_DEPLOYMENT_ANALYSIS: "matrixDeploymentAnalysis", MATRIX_ALLOCATION_ANALYSIS: "matrixAllocationAnalysis", MATRIX_COVERAGE_ANALYSIS: "matrixCoverageAnalysis", MATRIX_RISK_ANALYSIS: "matrixRiskAnalysis", MATRIX_QUESTION: "matrixQuestionAnswer" });

function round(value, digits = 2) { const number = Number(value); return Number.isFinite(number) ? Number(number.toFixed(digits)) : 0; }
function normalizeScore(value) { const number = Number(value); if (!Number.isFinite(number)) return 0; return Math.max(0, Math.min(100, Math.round(number > 0 && number <= 1 ? number * 100 : number))); }
function summarizeReplay(payload = {}) {
  const result = payload.result || payload;
  return {
    deploymentVersionId: result.deploymentVersionId || result.deployment_version_id || null,
    symbols: (result.symbols || []).slice(0, 100), total_return_pct: result.total_return_pct, max_drawdown_pct: result.max_drawdown_pct,
    sharpe: result.sharpe, sortino: result.sortino, completed_trades: result.completed_trades, win_rate_pct: result.win_rate_pct,
    profit_factor: result.profit_factor, capital_usage_pct: result.capital_usage_pct, total_fees_paid: result.total_fees_paid,
    estimated_slippage_cost: result.estimated_slippage_cost, sector_exposure: (result.sector_exposure || []).slice(0, 30),
    strategy_utilization: (result.strategy_utilization || []).slice(0, 30), allocation_utilization: (result.allocation_utilization || []).slice(0, 80),
    regime_breakdown: result.regime_breakdown || {}, symbol_attribution: (result.symbol_attribution || []).slice(0, 50), validation: result.validation || {},
  };
}

function buildMatrixAudit(dashboard = {}) {
  const cells = dashboard.matrix?.cells || []; const strategies = dashboard.strategies || [];
  const active = cells.filter((cell) => String(cell.status).toUpperCase() === "ACTIVE" && cell.selectedExperimentId);
  const pending = cells.filter((cell) => String(cell.status).toUpperCase() === "PENDING"); const sitOut = cells.filter((cell) => String(cell.status).toUpperCase() === "SIT_OUT");
  const utilization = new Map(); const sectors = new Map();
  active.forEach((cell) => { const current = utilization.get(cell.selectedExperimentId) || { experimentId: cell.selectedExperimentId, strategyName: cell.strategyName || strategies.find((item) => item.experimentId === cell.selectedExperimentId)?.name || "Unknown", cells: 0, allocationPct: 0 }; current.cells += 1; current.allocationPct += Number(cell.allocationPct || 0); utilization.set(cell.selectedExperimentId, current); sectors.set(cell.sector, (sectors.get(cell.sector) || 0) + Number(cell.allocationPct || 0)); });
  const assignedCapitalPct = strategies.reduce((sum, item) => sum + Number(item.assignedCapitalPct || 0), 0);
  return {
    totalCells: cells.length, activeCells: active.length, pendingCells: pending.length, sitOutCells: sitOut.length,
    emptyCells: cells.filter((cell) => !cell.selectedExperimentId && String(cell.status).toUpperCase() !== "SIT_OUT").length,
    coveragePct: cells.length ? round(active.length / cells.length * 100) : 0, assignedCapitalPct: round(assignedCapitalPct), idleCapitalPct: round(Math.max(0, 100 - assignedCapitalPct)),
    guardrailsValid: Boolean(dashboard.guardrails?.valid), guardrailViolations: dashboard.guardrails?.violations || [],
    duplicateStrategies: [...utilization.values()].filter((item) => item.cells > 1).sort((a, b) => b.cells - a.cells), strategyUtilization: [...utilization.values()].sort((a, b) => b.cells - a.cells),
    unusedStrategies: strategies.filter((strategy) => !utilization.has(strategy.experimentId)).map((strategy) => ({ experimentId: strategy.experimentId, strategyName: strategy.name, assignedCapitalPct: strategy.assignedCapitalPct })),
    sectorConcentration: [...sectors.entries()].map(([sector, allocationPct]) => ({ sector, allocationPct: round(allocationPct) })).sort((a, b) => b.allocationPct - a.allocationPct),
  };
}

function createMatrixEvidence(dashboard, audit, replaySnapshot) {
  const items = []; const push = (payload) => { const item = createEvidenceItem(payload); if (item) items.push(item); }; const deploymentId = dashboard.deploymentSetId || "current-matrix";
  [["TotalCells", audit.totalCells], ["ActiveCells", audit.activeCells], ["SitOutCells", audit.sitOutCells], ["CoveragePct", audit.coveragePct], ["IdleCapitalPct", audit.idleCapitalPct]].forEach(([metricName, metricValue]) => push({ sourceType: "MATRIX_CONFIGURATION", sourceId: deploymentId, metricName, metricValue, timestamp: dashboard.generatedAt, interpretation: `Deterministic ${metricName} from the canonical deployment matrix.`, strength: "HIGH" }));
  (dashboard.matrix?.cells || []).slice(0, 80).forEach((cell) => { push({ sourceType: "DEPLOYMENT", sourceId: cell.key, metricName: "CellStatus", metricValue: cell.status, timestamp: dashboard.generatedAt, interpretation: `${cell.sector} × ${cell.regime} routes ${cell.strategyName || "no strategy"}.`, strength: "HIGH" }); if (cell.selectedExperimentId) push({ sourceType: "ALLOCATION", sourceId: cell.key, metricName: "AllocationPct", metricValue: cell.allocationPct, timestamp: dashboard.generatedAt, interpretation: `Saved allocation for ${cell.sector} × ${cell.regime}.`, strength: "HIGH" }); });
  (dashboard.strategies || []).forEach((strategy) => { [["ReadinessScore", strategy.readinessScore], ["ValidationScore", strategy.validationScore], ["RobustnessScore", strategy.robustnessScore], ["AssignedCapitalPct", strategy.assignedCapitalPct]].forEach(([metricName, metricValue]) => push({ sourceType: metricName === "AssignedCapitalPct" ? "ALLOCATION" : metricName === "ValidationScore" ? "VALIDATION" : "LIFECYCLE", sourceId: strategy.strategyVersionId || strategy.experimentId, metricName, metricValue, timestamp: dashboard.generatedAt, interpretation: `${strategy.name} ${metricName} from Strategy Lab.`, strength: "HIGH" })); });
  const simulation = dashboard.simulation?.metrics || {}; [["ExpectedReturn", simulation.expectedReturn], ["ExpectedDrawdown", simulation.expectedDrawdown], ["Sharpe", simulation.sharpe], ["CapitalUsage", simulation.capitalUsage]].forEach(([metricName, metricValue]) => push({ sourceType: "PORTFOLIO_SIMULATION", sourceId: deploymentId, metricName, metricValue, timestamp: dashboard.generatedAt, interpretation: `Current deterministic allocation simulation ${metricName}.`, strength: "MEDIUM" }));
  const replay = replaySnapshot?.resultJson; if (replay) [["TotalReturnPct", replay.total_return_pct], ["MaxDrawdownPct", replay.max_drawdown_pct], ["Sharpe", replay.sharpe], ["CompletedTrades", replay.completed_trades], ["WinRatePct", replay.win_rate_pct]].forEach(([metricName, metricValue]) => push({ sourceType: "MATRIX_REPLAY", sourceId: replaySnapshot.id, metricName, metricValue, timestamp: replaySnapshot.createdAt, interpretation: `Latest saved matrix replay ${metricName}.`, strength: "HIGH" }));
  return items.slice(0, 160);
}

function createMatrixCopilotService({ prisma, aiService, getDeploymentAllocationDashboard, memoryIngestionService = null }) {
  const dbRun = (operation) => prisma.run ? prisma.run(operation) : operation(prisma);
  async function recordReplay(userId, request, result) { const ownerId = requireUserId(userId); const summary = summarizeReplay(result); const replayConfig = { symbols: (request.symbols || request.universeSymbols || summary.symbols || []).slice(0, 100), universeSymbols: (request.universeSymbols || request.symbols || summary.symbols || []).slice(0, 100), universeMembers: (request.universeMembers || []).slice(0, 100).map((item) => ({ symbol: item.symbol, sector: item.sector, industry: item.industry })), period: request.period || "2y", startDate: request.startDate || null, endDate: request.endDate || null, benchmark: request.benchmark || "SPY", initialCash: Number(request.initialCash || 100000), feePerTrade: Number(request.feePerTrade || 1), executionAssumptions: request.executionAssumptions || {}, positionSizing: request.positionSizing || {}, riskPerTrade: Number(request.riskPerTrade || 0.01) }; const record = await dbRun((db) => db.matrixReplaySnapshot.create({ data: { userId: ownerId, deploymentSetId: summary.deploymentVersionId || null, period: String(request.period || ""), symbolsJson: summary.symbols, replayConfigJson: replayConfig, resultJson: summary } })); if (memoryIngestionService) { const { matrixReplayEvent } = require("../../memory/services/memoryEvents"); await memoryIngestionService.recordFromMatrix(matrixReplayEvent(record)); } return record; }
  async function buildContext(userId, workflow, question = "") { const ownerId = requireUserId(userId); const [dashboard, replaySnapshot] = await Promise.all([getDeploymentAllocationDashboard({ userId: ownerId }), dbRun((db) => db.matrixReplaySnapshot.findFirst({ where: { userId: ownerId }, orderBy: { createdAt: "desc" } }))]); const audit = buildMatrixAudit(dashboard); return { workflow, question: String(question || ""), readOnly: true, dashboard: { generatedAt: dashboard.generatedAt, deploymentSetId: dashboard.deploymentSetId, allocationMethod: dashboard.allocationMethod, guardrails: dashboard.guardrails, activeSet: dashboard.activeSet, strategies: dashboard.strategies, matrix: dashboard.matrix, simulation: dashboard.simulation, rebalance: dashboard.rebalance }, audit, latestReplay: replaySnapshot ? { id: replaySnapshot.id, period: replaySnapshot.period, createdAt: replaySnapshot.createdAt, replayConfigJson: replaySnapshot.replayConfigJson || {}, resultJson: replaySnapshot.resultJson } : null, availableEvidence: createMatrixEvidence(dashboard, audit, replaySnapshot), limitations: replaySnapshot ? [] : ["No saved matrix replay is available. Run Matrix Replay explicitly before requesting replay analysis."] }; }
  async function run(userId, body = {}) { if (!aiService?.isConfigured?.()) { const error = new Error("AI Matrix Copilot is not configured."); error.statusCode = 503; throw error; } const workflow = String(body.workflow || "MATRIX_AUDIT").toUpperCase(); if (!MATRIX_WORKFLOWS.includes(workflow)) { const error = new Error("Unsupported Matrix Copilot workflow."); error.statusCode = 400; throw error; } const question = String(body.question || "").trim(); if (workflow === "MATRIX_QUESTION" && !question) { const error = new Error("A matrix question is required."); error.statusCode = 400; throw error; } const context = await buildContext(userId, workflow, question); const output = await aiService[FEATURE_METHODS[workflow]](userId, context); const evidence = normalizeEvidenceReferences(output.evidence, context.availableEvidence); return { generatedAt: new Date().toISOString(), workflow, readOnly: true, audit: context.audit, replayFreshness: context.latestReplay?.createdAt || null, response: { ...output, evidence, confidenceScore: normalizeScore(output.confidenceScore), limitations: [...new Set([...(output.limitations || []), ...context.limitations, ...(evidence.length ? [] : ["Insufficient evidence available."])])] } }; }
  return { buildContext, recordReplay, run };
}

module.exports = { FEATURE_METHODS, MATRIX_WORKFLOWS, buildMatrixAudit, createMatrixCopilotService, createMatrixEvidence, summarizeReplay };
