const crypto = require("node:crypto");
const { validateAllocationPlan, buildAllocationSimulation } = require("./strategyAllocationService");
const { validateMatrixProposalShape, proposalError } = require("./matrixScenarioContract");
const { summarizeReplay } = require("./matrixCopilot.service");

function clone(value) { return JSON.parse(JSON.stringify(value)); }
function round(value, digits = 2) { const number = Number(value); return Number.isFinite(number) ? Number(number.toFixed(digits)) : null; }
function cellKey(sector, regime) { return `${String(sector)}::${String(regime)}`; }
function replayMetrics(result) { const value = result?.result || result || {}; return { totalReturnPct: value.total_return_pct ?? null, cagr: value.cagr ?? null, sharpe: value.sharpe ?? null, sortino: value.sortino ?? null, maxDrawdownPct: value.max_drawdown_pct ?? null, volatilityPct: value.volatility_pct ?? null, calmar: value.calmar ?? null, turnover: value.turnover ?? null, transactionCosts: Number(value.total_fees_paid || 0) + Number(value.estimated_slippage_cost || 0), completedTrades: value.completed_trades ?? null, winRatePct: value.win_rate_pct ?? null, strategyUtilization: value.strategy_utilization || [], sectorExposure: value.sector_exposure || [], regimeAttribution: value.regime_breakdown || {}, allocationUtilization: value.allocation_utilization || [] }; }
function metricDelta(current, proposed) { const result = {}; for (const key of Object.keys({ ...current, ...proposed })) { if (typeof current[key] === "number" && typeof proposed[key] === "number") result[key] = round(proposed[key] - current[key]); } return result; }

function applyProposal(dashboard, proposal) {
  validateMatrixProposalShape(proposal); if (proposal.deploymentSetId !== dashboard.deploymentSetId) throw proposalError("Proposal deployment set is stale or does not belong to the current user.");
  const matrix = clone(dashboard.matrix); const strategies = clone(dashboard.strategies || []); const strategyById = new Map(strategies.map((item) => [item.experimentId, item])); const cellByKey = new Map(matrix.cells.map((cell) => [cell.key || cellKey(cell.sector, cell.regime), cell]));
  const requireCell = (action, index) => { const cell = cellByKey.get(cellKey(action.sector, action.regime)); if (!cell) throw proposalError(`Unknown matrix cell ${cellKey(action.sector, action.regime)}.`, index); return cell; };
  const requireStrategy = (id, versionId, index) => { const strategy = strategyById.get(id); if (!strategy) throw proposalError("Proposed strategy is not owned by this user or is unavailable.", index); if (versionId && strategy.strategyVersionId !== versionId) throw proposalError("Proposed strategy version is stale or not owned by this user.", index); if (["BLOCKED", "INELIGIBLE"].includes(String(strategy.status).toUpperCase()) || Number(strategy.readinessScore || 0) < 1) throw proposalError(`${strategy.name} is not lifecycle/deployment eligible.`, index); return strategy; };
  proposal.actions.forEach((action, index) => {
    if (["SET_SECTOR_CAP", "SET_STRATEGY_CAP", "REDISTRIBUTE_IDLE_CAPITAL", "NORMALIZE_ALLOCATIONS"].includes(action.actionType)) return;
    const cell = requireCell(action, index); if (action.currentStrategyId && cell.selectedExperimentId !== action.currentStrategyId) throw proposalError(`Action ${index + 1} references a stale current strategy.`, index); if (Math.abs(Number(cell.allocationPct || 0) - Number(action.currentAllocation)) > 0.01) throw proposalError(`Action ${index + 1} references a stale current allocation.`, index);
    if (["SET_CELL_TO_SIT_OUT", "DISABLE_CELL"].includes(action.actionType)) Object.assign(cell, { selectedExperimentId: null, selectedStrategyVersionId: null, strategyName: null, strategyKey: cell.key, allocationPct: 0, status: "SIT_OUT", evidenceStatus: "Sit out" });
    else if (action.actionType === "SET_CELL_ALLOCATION") cell.allocationPct = Number(action.proposedAllocation);
    else { const strategy = requireStrategy(action.proposedStrategyId, action.proposedStrategyVersionId, index); Object.assign(cell, { selectedExperimentId: strategy.experimentId, selectedStrategyVersionId: strategy.strategyVersionId, strategyName: strategy.name, strategyKey: strategy.strategyVersionId || strategy.experimentId, allocationPct: Number(action.proposedAllocation), status: "ACTIVE", evidenceStatus: "Validated" }); }
  });
  proposal.actions.filter((action) => action.actionType === "SET_SECTOR_CAP").forEach((action) => { const cells = matrix.cells.filter((cell) => cell.sector === action.sector && cell.status !== "SIT_OUT"); const total = cells.reduce((sum, cell) => sum + Number(cell.allocationPct || 0), 0); if (total > action.proposedAllocation && total > 0) cells.forEach((cell) => { cell.allocationPct = round(Number(cell.allocationPct || 0) * action.proposedAllocation / total, 4); }); });
  proposal.actions.filter((action) => action.actionType === "SET_STRATEGY_CAP").forEach((action, index) => { requireStrategy(action.currentStrategyId || action.proposedStrategyId, action.currentStrategyVersionId || action.proposedStrategyVersionId, index); const cells = matrix.cells.filter((cell) => cell.selectedExperimentId === (action.currentStrategyId || action.proposedStrategyId) && cell.status !== "SIT_OUT"); const total = cells.reduce((sum, cell) => sum + Number(cell.allocationPct || 0), 0); if (total > action.proposedAllocation && total > 0) cells.forEach((cell) => { cell.allocationPct = round(Number(cell.allocationPct || 0) * action.proposedAllocation / total, 4); }); });
  if (proposal.actions.some((action) => action.actionType === "NORMALIZE_ALLOCATIONS")) { const active = matrix.cells.filter((cell) => cell.status !== "SIT_OUT"); const total = active.reduce((sum, cell) => sum + Number(cell.allocationPct || 0), 0); if (total > 100) active.forEach((cell) => { cell.allocationPct = round(Number(cell.allocationPct || 0) * 100 / total, 4); }); }
  if (proposal.actions.some((action) => action.actionType === "REDISTRIBUTE_IDLE_CAPITAL")) { const active = matrix.cells.filter((cell) => cell.status === "ACTIVE" && cell.selectedExperimentId); const used = strategies.reduce((sum, item) => sum + Number(item.assignedCapitalPct || 0), 0); const idle = Math.max(0, 100 - used); if (active.length && idle > 0) active.forEach((cell) => { cell.allocationPct = round(Number(cell.allocationPct || 0) + idle / active.length, 4); }); }
  const validation = validateAllocationPlan({ strategies, matrixCells: matrix.cells, guardrails: dashboard.guardrails?.config }); if (!validation.valid) { const error = proposalError(validation.errors[0] || "Proposed matrix failed allocation validation."); error.details = { errors: validation.errors }; throw error; }
  return { matrix, strategies, validation, simulation: buildAllocationSimulation({ strategies, matrixCells: matrix.cells }) };
}

function createMatrixScenarioService({ runMatrixReplay }) {
  const cache = new Map();
  async function simulate({ userId, dashboard, latestReplay, proposal }) { const proposed = applyProposal(dashboard, proposal); const replayConfig = latestReplay?.replayConfigJson || null; const currentReplay = latestReplay?.resultJson || null; const hash = crypto.createHash("sha256").update(JSON.stringify({ userId, deploymentSetId: dashboard.deploymentSetId, matrix: proposed.matrix, replayConfig })).digest("hex"); if (cache.has(hash)) return clone(cache.get(hash)); let proposedReplay = null; if (replayConfig?.symbols?.length) proposedReplay = summarizeReplay(await runMatrixReplay({ userId, body: replayConfig, matrixOverride: proposed.matrix })); const currentMetrics = replayMetrics(currentReplay); const proposedMetrics = replayMetrics(proposedReplay); const comparison = { simulationMethod: proposedReplay ? "HISTORICAL_MATRIX_REPLAY" : "STATIC_ALLOCATION_AUDIT", current: { audit: { activeCells: dashboard.matrix.cells.filter((cell) => cell.status === "ACTIVE").length, sitOutCells: dashboard.matrix.cells.filter((cell) => cell.status === "SIT_OUT").length }, replay: currentMetrics, portfolio: dashboard.simulation }, proposed: { audit: { activeCells: proposed.matrix.cells.filter((cell) => cell.status === "ACTIVE").length, sitOutCells: proposed.matrix.cells.filter((cell) => cell.status === "SIT_OUT").length }, replay: proposedMetrics, portfolio: proposed.simulation }, delta: { replay: metricDelta(currentMetrics, proposedMetrics) }, validation: proposed.validation, matrixDiff: proposed.matrix.cells.filter((cell, index) => JSON.stringify(cell) !== JSON.stringify(dashboard.matrix.cells[index])).map((cell) => ({ before: dashboard.matrix.cells.find((item) => item.key === cell.key), after: cell })), replayAvailable: Boolean(proposedReplay), dataFreshness: { currentReplayAt: latestReplay?.createdAt || null, dashboardAt: dashboard.generatedAt } }; cache.set(hash, comparison); setTimeout(() => cache.delete(hash), 5 * 60 * 1000).unref?.(); return clone(comparison); }
  return { applyProposal, simulate };
}
module.exports = { applyProposal, createMatrixScenarioService, metricDelta, replayMetrics };
