const { createEvidenceItem, normalizeEvidenceReferences } = require("./strategyCopilotEvidence.service");
const { validateMatrixProposalShape } = require("./matrixScenarioContract");

function normalizeScore(value) { const number = Number(value); if (!Number.isFinite(number)) return 0; return Math.max(0, Math.min(100, Math.round(number > 0 && number <= 1 ? number * 100 : number))); }
function scenarioEvidence(comparison, deploymentSetId, index = 0) { const items = []; const sourceId = `scenario:${deploymentSetId}:${index}`; const push = (sourceType, metricName, metricValue, interpretation, strength = "HIGH") => { const item = createEvidenceItem({ sourceType, sourceId, metricName, metricValue, interpretation, strength }); if (item) items.push(item); }; const replay = comparison.proposed?.replay || {}; [["TotalReturnPct", replay.totalReturnPct], ["Sharpe", replay.sharpe], ["MaxDrawdownPct", replay.maxDrawdownPct], ["CompletedTrades", replay.completedTrades], ["TransactionCosts", replay.transactionCosts]].forEach(([name, value]) => push("MATRIX_REPLAY", name, value, `Deterministic proposed matrix replay ${name}.`)); const metrics = comparison.proposed?.portfolio?.metrics || {}; [["ExpectedReturn", metrics.expectedReturn], ["ExpectedDrawdown", metrics.expectedDrawdown], ["Sharpe", metrics.sharpe], ["CapitalUsage", metrics.capitalUsage]].forEach(([name, value]) => push("PORTFOLIO_SIMULATION", name, value, `Deterministic proposed portfolio impact ${name}.`, "MEDIUM")); push("MATRIX_CONFIGURATION", "ActiveCells", comparison.proposed?.audit?.activeCells, "Proposed active matrix cell count."); push("MATRIX_CONFIGURATION", "SitOutCells", comparison.proposed?.audit?.sitOutCells, "Proposed sit-out matrix cell count."); return items; }

function createMatrixAdvisorService({ aiService, matrixCopilotService, scenarioService }) {
  async function baseContext(userId, workflow, question) { const context = await matrixCopilotService.buildContext(userId, "MATRIX_AUDIT", question); return { ...context, workflow, question: String(question || ""), advisoryOnly: true, noChangesApplied: true }; }
  async function recommend(userId, body = {}) { const context = await baseContext(userId, "MATRIX_RECOMMENDATION", body.question || "Identify the most material matrix weakness."); const output = await aiService.matrixRecommendation(userId, context); return { generatedAt: new Date().toISOString(), advisoryOnly: true, noChangesApplied: true, response: { ...output, evidence: normalizeEvidenceReferences(output.evidence, context.availableEvidence), confidenceScore: normalizeScore(output.confidenceScore), limitations: [...new Set([...(output.limitations || []), ...(context.limitations || [])])] } }; }
  async function resolveProposal(userId, context, body) { const proposal = body.proposal || await aiService.matrixScenarioProposal(userId, { ...context, workflow: "MATRIX_SCENARIO_PROPOSAL", objective: String(body.question || body.objective || "Improve the current matrix using available evidence.") }); proposal.confidence = normalizeScore(proposal.confidence); proposal.evidence = normalizeEvidenceReferences(proposal.evidence, context.availableEvidence); return validateMatrixProposalShape(proposal); }
  async function scenario(userId, body = {}) { const context = await baseContext(userId, "MATRIX_SCENARIO_PROPOSAL", body.question || body.objective); const proposal = await resolveProposal(userId, context, body); const comparison = await scenarioService.simulate({ userId, dashboard: context.dashboard, latestReplay: context.latestReplay, proposal }); const availableEvidence = [...context.availableEvidence, ...scenarioEvidence(comparison, context.dashboard.deploymentSetId)]; const interpretation = await aiService.matrixScenarioInterpretation(userId, { ...context, workflow: "MATRIX_SCENARIO_INTERPRETATION", proposal, deterministicComparison: comparison, availableEvidence }); return { generatedAt: new Date().toISOString(), advisoryOnly: true, noChangesApplied: true, proposal, comparison, response: { ...interpretation, evidence: normalizeEvidenceReferences(interpretation.evidence, availableEvidence), confidenceScore: normalizeScore(interpretation.confidenceScore), limitations: [...new Set([...(interpretation.limitations || []), ...(context.limitations || []), ...(comparison.replayAvailable ? [] : ["Historical Matrix Replay was unavailable; comparison uses static allocation audit only."])])] } }; }
  async function compare(userId, body = {}) { if (!Array.isArray(body.proposals) || body.proposals.length < 2 || body.proposals.length > 4) { const error = new Error("Provide between two and four matrix proposals to compare."); error.statusCode = 400; throw error; } const context = await baseContext(userId, "MATRIX_ALTERNATIVE_COMPARISON", body.question || "Compare these matrix alternatives."); const proposals = body.proposals.map((proposal) => { proposal.confidence = normalizeScore(proposal.confidence); proposal.evidence = normalizeEvidenceReferences(proposal.evidence, context.availableEvidence); return validateMatrixProposalShape(proposal); }); const comparisons = []; for (const proposal of proposals) comparisons.push(await scenarioService.simulate({ userId, dashboard: context.dashboard, latestReplay: context.latestReplay, proposal })); const availableEvidence = [...context.availableEvidence, ...comparisons.flatMap((item, index) => scenarioEvidence(item, context.dashboard.deploymentSetId, index))]; const output = await aiService.matrixAlternativeComparison(userId, { ...context, workflow: "MATRIX_ALTERNATIVE_COMPARISON", proposals, deterministicComparisons: comparisons, availableEvidence }); return { generatedAt: new Date().toISOString(), advisoryOnly: true, noChangesApplied: true, proposals, comparisons, response: { ...output, rankings: (output.rankings || []).map((item) => ({ ...item, confidenceScore: normalizeScore(item.confidenceScore) })), evidence: normalizeEvidenceReferences(output.evidence, availableEvidence), limitations: [...new Set([...(output.limitations || []), ...(context.limitations || [])])] } }; }
  return { compare, recommend, scenario };
}
module.exports = { createMatrixAdvisorService, scenarioEvidence };
