export const DEFAULT_PARAMETER_SWEEP = {
  symbol: "AAPL",
  universeId: "",
  universeMode: "SINGLE",
  topN: "10",
  period: "2y",
  emaFastMin: "10",
  emaFastMax: "30",
  emaFastStep: "5",
  emaSlowMin: "40",
  emaSlowMax: "100",
  emaSlowStep: "5",
  rsiMin: "50",
  rsiMax: "70",
  rsiStep: "5",
  maxCombinations: "500",
};

export const DEFAULT_STRATEGY_EXPERIMENT = {
  name: "Momentum Lab",
  description: "",
  status: "DRAFT",
  settings: {
    objective: "max_risk_adjusted_return",
    template: "Momentum",
    universeType: "SINGLE",
    marketBias: "US_AND_SGX",
    primaryTimeframe: "1D",
    entryTimeframe: "1H",
    sizingMethod: "risk_per_trade",
    sizingPreviewCapital: "50000",
    maxDrawdown: "12",
    maxPositionSize: "8",
    maxSectorExposure: "30",
    maxDailyLoss: "3",
    robustnessMode: false,
    capitalSimulation: "50000",
    strategyPrompt: "",
    rules: [
      { id: "trend", group: "Signal", operator: "WHEN", left: "EMA(20)", comparator: ">", right: "EMA(50)", connector: "AND" },
      { id: "momentum", group: "Entry", operator: "AND", left: "RSI(14)", comparator: "between", right: "45 and 68", connector: "AND" },
      { id: "volume", group: "Entry", operator: "AND", left: "Volume", comparator: ">", right: "SMA(Volume, 20)", connector: "THEN BUY" },
    ],
    emaFast: "20",
    emaSlow: "50",
    rsiThreshold: "55",
    atrStopMultiple: "1.5",
    atrTakeProfitMultiple: "8",
    trailingStopAtrMultiple: "2",
    riskPerTrade: "0.01",
    signalThreshold: "60",
    technicalWeight: "0.45",
    regimeWeight: "0.25",
    newsWeight: "0.15",
    openaiWeight: "0.15",
    regimeFilter: true,
    newsFilter: true,
    marketHoursOnly: true,
    earningsFilter: true,
    universeId: "",
    universeName: "",
    allowedSectors: "Technology, Communication Services",
    allowedRegimes: "BULL_LOW_VOL, BULL_HIGH_VOL, SIDEWAYS",
    instrumentTypes: "SINGLE_STOCK, ETF",
    volatilityMin: "0",
    volatilityMax: "0.03",
    liquidityFloor: "1000000",
    holdingPeriodDays: "15",
    regimeOverlays: {
      BULL_HIGH_VOL: {
        atrStopMultiple: "2.2",
        riskPerTrade: "0.0075",
        signalThreshold: "64",
      },
      BEAR_HIGH_VOL: {
        atrStopMultiple: "2.5",
        riskPerTrade: "0.004",
        signalThreshold: "72",
      },
    },
    allocationMatrix: {},
  },
};

export const STRATEGY_OBJECTIVES = {
  max_risk_adjusted_return: {
    label: "Max risk-adjusted return",
    template: "Momentum",
    description: "Prioritizes Sharpe, expectancy, and stable drawdowns over raw return.",
    defaults: {
      template: "Momentum",
      signalThreshold: "60",
      maxDrawdown: "12",
      riskPerTrade: "0.01",
      technicalWeight: "0.45",
      regimeWeight: "0.25",
      newsWeight: "0.15",
      openaiWeight: "0.15",
    },
  },
  minimize_drawdown: {
    label: "Minimize drawdown",
    template: "Trend Following",
    description: "Favors wider evidence gates, lower risk, and stronger regime confirmation.",
    defaults: {
      template: "Trend Following",
      signalThreshold: "68",
      maxDrawdown: "8",
      riskPerTrade: "0.006",
      atrStopMultiple: "2",
      technicalWeight: "0.4",
      regimeWeight: "0.35",
      newsWeight: "0.15",
      openaiWeight: "0.1",
    },
  },
  steady_income: {
    label: "Steady income",
    template: "Value",
    description: "Lower frequency, broader macro context, and more patient exits.",
    defaults: {
      template: "Value",
      primaryTimeframe: "1W",
      entryTimeframe: "1D",
      signalThreshold: "64",
      riskPerTrade: "0.008",
      technicalWeight: "0.3",
      regimeWeight: "0.3",
      newsWeight: "0.25",
      openaiWeight: "0.15",
    },
  },
  catch_breakouts: {
    label: "Catch breakouts",
    template: "Breakout",
    description: "Accepts more whipsaw risk in exchange for earlier expansion signals.",
    defaults: {
      template: "Breakout",
      signalThreshold: "58",
      rsiThreshold: "60",
      atrStopMultiple: "1.8",
      atrTakeProfitMultiple: "5",
      trailingStopAtrMultiple: "2.2",
      technicalWeight: "0.5",
      regimeWeight: "0.25",
      newsWeight: "0.15",
      openaiWeight: "0.1",
    },
  },
  custom: {
    label: "Custom",
    template: "Custom",
    description: "No presets applied. Use this when you know exactly what behavior you want.",
    defaults: {},
  },
};

export const STRATEGY_TEMPLATES = {
  "Trend Following": {
    description: "Follow sustained directional moves with regime confirmation and trailing exits.",
    guardrails: ["Requires trend alignment", "Avoids low-liquidity names", "Trailing stop required"],
    settings: {
      template: "Trend Following",
      emaFast: "20",
      emaSlow: "100",
      rsiThreshold: "58",
      atrStopMultiple: "2",
      atrTakeProfitMultiple: "6",
      trailingStopAtrMultiple: "2.5",
      technicalWeight: "0.5",
      regimeWeight: "0.3",
      newsWeight: "0.1",
      openaiWeight: "0.1",
      rules: [
        { id: "trend-daily", group: "Signal", operator: "WHEN", left: "EMA(20)", comparator: ">", right: "EMA(50)", connector: "AND" },
        { id: "price-strength", group: "Entry", operator: "AND", left: "Close", comparator: ">", right: "EMA(20)", connector: "AND" },
        { id: "risk-stop", group: "Exit", operator: "THEN", left: "ATR trailing stop", comparator: "=", right: "2.5x ATR", connector: "MANAGE" },
      ],
    },
  },
  "Mean Reversion": {
    description: "Look for quality pullbacks after short-term exhaustion, with tighter validation.",
    guardrails: ["Needs higher sample size", "Avoids bear high-vol regimes", "Tighter max loss"],
    settings: {
      template: "Mean Reversion",
      emaFast: "10",
      emaSlow: "50",
      rsiThreshold: "35",
      atrStopMultiple: "1.3",
      atrTakeProfitMultiple: "3",
      trailingStopAtrMultiple: "1.8",
      technicalWeight: "0.55",
      regimeWeight: "0.2",
      newsWeight: "0.15",
      openaiWeight: "0.1",
      rules: [
        { id: "oversold", group: "Signal", operator: "WHEN", left: "RSI(14)", comparator: "<", right: "35", connector: "AND" },
        { id: "trend-filter", group: "Market", operator: "AND", left: "EMA(20)", comparator: ">=", right: "EMA(50)", connector: "AND" },
        { id: "exit-revert", group: "Exit", operator: "THEN", left: "Take profit", comparator: "=", right: "3x ATR", connector: "MANAGE" },
      ],
    },
  },
  Breakout: {
    description: "Catch range expansion after price and volume confirmation.",
    guardrails: ["Volume confirmation required", "Gap risk warning", "Needs false-breakout review"],
    settings: {
      template: "Breakout",
      emaFast: "20",
      emaSlow: "50",
      rsiThreshold: "60",
      atrStopMultiple: "1.8",
      atrTakeProfitMultiple: "5",
      trailingStopAtrMultiple: "2.2",
      technicalWeight: "0.5",
      regimeWeight: "0.25",
      newsWeight: "0.15",
      openaiWeight: "0.1",
      rules: [
        { id: "range-break", group: "Signal", operator: "WHEN", left: "Close", comparator: ">", right: "20-day high", connector: "AND" },
        { id: "volume-break", group: "Entry", operator: "AND", left: "Volume", comparator: ">", right: "SMA(Volume, 20)", connector: "AND" },
        { id: "false-break", group: "Validation", operator: "AND", left: "Close", comparator: ">", right: "EMA(20)", connector: "THEN BUY" },
      ],
    },
  },
  Momentum: {
    description: "Rank strong trend and price behavior while filtering for risk and validation quality.",
    guardrails: ["Avoid overconcentrated sectors", "Requires confidence calibration", "Manual review for high-risk names"],
    settings: DEFAULT_STRATEGY_EXPERIMENT.settings,
  },
  Value: {
    description: "Longer-horizon setup that favors stable trend confirmation and lower trading frequency.",
    guardrails: ["Requires longer holding assumptions", "Macro/news weighting increased", "No intraday chasing"],
    settings: {
      template: "Value",
      primaryTimeframe: "1W",
      entryTimeframe: "1D",
      emaFast: "50",
      emaSlow: "200",
      rsiThreshold: "50",
      atrStopMultiple: "3",
      atrTakeProfitMultiple: "8",
      trailingStopAtrMultiple: "3",
      technicalWeight: "0.3",
      regimeWeight: "0.3",
      newsWeight: "0.25",
      openaiWeight: "0.15",
      rules: [
        { id: "value-trend", group: "Market", operator: "WHEN", left: "Close", comparator: ">", right: "EMA(50)", connector: "AND" },
        { id: "value-risk", group: "Risk", operator: "AND", left: "Volatility", comparator: "<", right: "0.03", connector: "THEN BUY" },
      ],
    },
  },
  "News Driven": {
    description: "Uses technical signals only after news/event risk is known and explainable.",
    guardrails: ["AI may adjust confidence only", "Blocks high-risk event windows", "Never creates signals from news alone"],
    settings: {
      template: "News Driven",
      technicalWeight: "0.3",
      regimeWeight: "0.2",
      newsWeight: "0.3",
      openaiWeight: "0.2",
      newsFilter: true,
      earningsFilter: true,
      rules: [
        { id: "technical-base", group: "Signal", operator: "WHEN", left: "EMA(20)", comparator: ">", right: "EMA(50)", connector: "AND" },
        { id: "news-risk", group: "Validation", operator: "AND", left: "Close", comparator: ">", right: "EMA(20)", connector: "AND" },
        { id: "event-window", group: "Validation", operator: "AND", left: "Volatility", comparator: "<", right: "0.03", connector: "THEN BUY" },
      ],
    },
  },
  "Volatility Expansion": {
    description: "Targets volatility expansion after compression, with strict stop and liquidity checks.",
    guardrails: ["Liquidity required", "Reduced size on high volatility", "Stops must be wider than noise"],
    settings: {
      template: "Volatility Expansion",
      emaFast: "15",
      emaSlow: "50",
      rsiThreshold: "57",
      atrStopMultiple: "2.2",
      atrTakeProfitMultiple: "5",
      trailingStopAtrMultiple: "2.4",
      rules: [
        { id: "atr-expansion", group: "Signal", operator: "WHEN", left: "ATR", comparator: ">", right: "1", connector: "AND" },
        { id: "price-confirm", group: "Entry", operator: "AND", left: "Close", comparator: ">", right: "EMA(20)", connector: "THEN BUY" },
      ],
    },
  },
  Pairs: {
    description: "Research scaffold for pair-style setups. Execution remains research-only.",
    guardrails: ["Requires correlation review", "No automatic execution", "Needs pair universe"],
    settings: {
      template: "Pairs",
      universeType: "CUSTOM_SCREEN",
      technicalWeight: "0.35",
      regimeWeight: "0.15",
      newsWeight: "0.2",
      openaiWeight: "0.3",
      rules: [
        { id: "spread", group: "Signal", operator: "WHEN", left: "EMA(20)", comparator: ">", right: "EMA(50)", connector: "AND" },
        { id: "correlation", group: "Validation", operator: "AND", left: "RSI(14)", comparator: "between", right: "45 and 68", connector: "THEN REVIEW" },
      ],
    },
  },
};

export const STRATEGY_BUILDER_SECTIONS = [
  "Intent",
  "Market",
  "Signal",
  "Execution",
  "Risk",
  "Validation",
];

export const STRATEGY_RULE_GROUPS = ["Market", "Signal", "Entry", "Risk", "Exit", "Validation"];
export const STRATEGY_RULE_CONNECTORS = ["AND", "OR", "NOT", "GROUP", "THEN BUY", "THEN REVIEW", "MANAGE"];

export const STRATEGY_EXPERIMENT_FIELDS = [
  ["emaFast", "EMA Fast"],
  ["emaSlow", "EMA Slow"],
  ["rsiThreshold", "RSI Threshold"],
  ["atrStopMultiple", "ATR Stop Multiple"],
  ["atrTakeProfitMultiple", "ATR Take Profit Multiple"],
  ["trailingStopAtrMultiple", "Trailing Stop Multiple"],
  ["riskPerTrade", "Risk Per Trade"],
  ["signalThreshold", "Signal Threshold"],
];

export const STRATEGY_WEIGHT_FIELDS = [
  ["technicalWeight", "Technical Weight"],
  ["regimeWeight", "Regime Weight"],
  ["newsWeight", "News Weight"],
  ["openaiWeight", "OpenAI Weight"],
];
